export const siteConfig = {
  name: "Bal Sansar Sanstha",
  shortName: "BSS",
  tagline: "Empowering Vulnerable Communities to Lead a Life with Dignity",
  description:
    "Bal Sansar Sanstha is a registered non-profit voluntary organization established in 1992 in Jaipur, Rajasthan. We work in Quality Education, Skill Development, Public Health, Women & Children's Empowerment, and Community Development.",
  url: "https://balsansarindia.com",
  email: "bss@balsansarindia.com",
  emailAlt: "bsansarindia@yahoo.co.in",
  phone: "+91-9829011880",
  address: {
    line1: "'Swasti', B-88, Saraswati Marg",
    line2: "Bajaj Nagar, Jaipur - 302015",
    state: "Rajasthan, India",
    full: "'Swasti', B-88, Saraswati Marg, Bajaj Nagar, Jaipur - 302015, Rajasthan, India",
  },
  founded: 1992,
  registration: {
    "12A": "AAATB9592LE20214",
    "80G": "AAATB9592LF20214",
    FCRA: "125560132",
    CSR: "CSR00058152",
  },
  social: {
    facebook: "https://www.facebook.com/BalSansarSansthaIndia/",
    twitter: "https://twitter.com/balsansarindia",
    instagram: "https://instagram.com/balsansarindia",
    linkedin: "https://www.linkedin.com/company/balsansarindia/",
    youtube: "https://youtube.com/@balsansarindia",
  },
  mission:
    "To empower vulnerable community groups enabling them to lead a life with dignity.",
  vision:
    "An equitable, corruption-free and just society where everyone gets opportunity to realise one's fullest potential in life, with no discrimination based on gender, religion, caste, creed, social, cultural and economic status.",
  objectives: [
    "Child Rights, Education & Development",
    "Skill-Entrepreneurship Development for Adolescents & Youth",
    "Community Health & Development",
    "Women Development & Gender Issues",
    "Research & Documentation",
    "Capacity Building",
    "Networking & Advocacy",
  ],
  impactNumbers: {
    beneficiaries: "50,000+",
    yearsOfService: "32+",
    gramPanchayats: "30+",
    volunteers: "200+",
    projects: "15+",
    districts: "5+",
  },
  nav: [
    { label: "Home", href: "/" },
    { label: "About", href: "/about" },
    {
      label: "Projects",
      href: "/projects",
      children: [
        { label: "All Projects", href: "/projects" },
        { label: "Bal Sansar Public School", href: "/projects/bsps" },
        { label: "SEDI", href: "/projects/sedi" },
        { label: "Taiyari", href: "/projects/taiyari" },
        { label: "Completed Projects", href: "/projects/completed" },
      ],
    },
    { label: "Members", href: "/members" },
    { label: "Impact Stories", href: "/stories" },
    { label: "Gallery", href: "/gallery" },
    { label: "Blog", href: "/blog" },
    { label: "Get Involved", href: "/get-involved" },
    { label: "Contact", href: "/contact" },
  ],
} as const;
